@startuml
box A new Hope - failure
participant Developer

participant Renovate

Renovate -> "Git Repository" : recognizes new Version and creates Pull Request
activate Renovate
activate "Git Repository"
deactivate Renovate

"Git Repository" -> Pipeline : new branch triggers Pipeline
activate Pipeline

Pipeline -> OpenRewrite : Pipeline runs OpenRewrite
activate OpenRewrite

OpenRewrite -> Pipeline : makes code changes
deactivate OpenRewrite

Pipeline -> "Git Repository" : creates Pull Request

"Git Repository" -> Pipeline : Pull Request triggers Pipeline

Pipeline -> "Git Repository" : fails and creates comment in Pull Request with DevSpace-URL

"Git Repository" -> Developer : notifies
activate Developer

Developer -> DevSpace : opens DevSpace
activate DevSpace
Developer -> DevSpace : fixes code changes

DevSpace -> "Git Repository" : pushes code changes
"Git Repository" -> Pipeline : git push triggers Pipeline

Pipeline -> "Git Repository" : successful

"Git Repository" -> Developer : notifies

"Developer" -> "Git Repository" : merges Pull Request

Developer -> DevSpace : deletes DevSpace
deactivate DevSpace

deactivate "Git Repository"

end box
@enduml