@startuml
box A new Hope - success
participant Developer

participant Renovate

Renovate -> "Git Repository" : recognizes new Version and creates Pull Request
activate Renovate
activate "Git Repository"
deactivate Renovate

"Git Repository" -> Pipeline : new branch triggers Pipeline
activate Pipeline

Pipeline -> "Angular CLI" : Pipeline runs "ng update"
activate "Angular CLI"

"Angular CLI" -> Pipeline : makes code changes
deactivate "Angular CLI"

Pipeline -> "Git Repository" : creates Pull Request

"Git Repository" -> Pipeline : Pull Request triggers Pipeline

Pipeline -> "Git Repository" : successful

"Developer" -> "Git Repository" : Developer merges Pull Request
deactivate "Git Repository"
activate Developer
deactivate Developer
end box
@enduml