name: Trigger Renovate

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40.1.12
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
