name: Trigger Renovate

on:
  push:
    branches:
      - main
  #schedule:
  #  - cron: '0 0 * * *' # Runs daily at midnight UTC
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40.1.12
        with:
          renovate-image: ghcr.io/gepardec/gepardec-renovate
          renovate-version: main-8b03812
          token: ${{ secrets.RENOVATE_TOKEN }}
          configurationFile: renovate-config.js
          docker-volumes: |
            /home/runner/work/renovate/renovate/quarkus-update:/github-action/quarkus-update
        env:
          LOG_LEVEL: debug
